import {StyleSheet }from 'react-native'
const styles = StyleSheet.create({
    container:{
        height:'100%',
        backgroundColor:'white',
    },
    header:{
        height:50,
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        borderBottomWidth:1,
        borderBottomColor:'#e0e0e0',
        backgroundColor:'white',
    },
    title:{
        fontWeight:'bold',
        fontSize:17,
        marginLeft:10
    },
    btnsetting:{
        marginRight:10
    },
    hello:{
        height:60,
        width:'100%',
        backgroundColor:'#f5f5f5',
        justifyContent:'center',
        alignItems:'center',
    },
    txthello:{
        fontWeight:'bold',
    },
    btnorder:{
        height:70,
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
        borderBottomWidth:0.5,
        borderBottomColor:'#e0e0e0'
    },
    description:{
        marginLeft:10,
    },
    txtoption:{
        fontWeight:'bold',
    },
    txtmission:{
        color:'#969696'
    },
    btnnoti:{
        height:70,
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
        borderBottomWidth:10,
        borderBottomColor:'#e0e0e0'
    },
    service:{
        height:50,
        width:'100%',
        marginLeft:10,
        justifyContent:'center',
        borderBottomColor:'#e0e0e0',
        borderBottomWidth:1,

    },
    signout:{
        height:120,
        width:'100%',
        backgroundColor:'#f5f5f5',
        justifyContent:'center',
        alignItems:'center',
    },
    btnsignout:{
        height:55,
        width:320,
        backgroundColor:'white',
        borderWidth:1.5,
        borderColor:'#999999',
        justifyContent:'center',
        alignItems:'center',
    },
    txtsignout:{
        fontWeight:'bold',
        justifyContent:'center',
        alignItems:'center'
    },

})
export default styles