import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container:{
        height:'100%'
    },
    header:{
        height:50,
        width:'100%',
        alignItems:'center',
        borderBottomWidth:0.2,
        borderBottomColor:'#e0e0e0',
        flexDirection:'row',
    },
    txttitle:{
        fontWeight:'bold',
        marginLeft:10,
        fontSize:25,
    },
    option:{
        flexDirection:'row',
        borderBottomWidth:0.2,
        borderBottomColor:'#e0e0e0',
        justifyContent:'space-evenly',
        height:50,
        alignItems:'center',
    },
    sort:{
        flexDirection:'row',
    },
    line:{
        width:1,
        height:13,
        backgroundColor:'#e0e0e0',
    },
    txtsort:{
        fontWeight:'bold',
        fontSize:17,
    },
    style:{
        height:50,
        width:'100%',
        justifyContent:'center',
        alignItems:"center",
    },
    list:{
        height:'auto', 
        backgroundColor:'#ffffff' 
    },
    imgF:{
        height:240,
        width:180,
        margin:10,
    },
    info:{
        justifyContent:'space-between',
        flexDirection:'row',
        marginLeft:10,
        marginRight:10,
    },
    txtprice:{
        fontWeight:'bold',
        fontSize:18,
    },
    txtname:{
        fontSize:15,
        marginLeft:10,
    }
})
export default styles