import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    background:{
        backgroundColor:'#DDDDDD',
        height:'100%'
    },
    header:{
        flexDirection:'row',
        justifyContent:'space-between',
        height:50,
        alignItems:'center',
        borderBottomColor:'silver',
        borderBottomWidth:0.5,
        backgroundColor:'#fff'
    },
    blank:{
        width:30,
        height:30,
    },
    Title:{
        fontSize:24,
        fontWeight:'bold',
    },
    searchbar:{
        height:60,
        justifyContent:'space-evenly',
        alignItems:'center',
        flexDirection:'row'
    },
    searchIp:{
        width:250,
        height:45,
    },
    Img:{
        width:'100%',
        height:250,
        marginVertical:10
    },
    fList:{
        backgroundColor:'white',
        height:'auto'
    },
    Offers:{
        height:30,
        justifyContent:'center'
    },
    txtOffers:{
        color:'grey',
        fontWeight:'bold',
        textAlign:'center',
        textDecorationLine:'underline'
    },
    txt1:{
        textAlign:'center',
        fontWeight:'bold',
        fontSize:20,
        marginTop:20
    },
    txt2:{
        textAlign:'center',
        fontSize:15,
        marginTop:5
    },
    ImgB:{
        width:175,
        height:175,
        margin:10
    },
    VM:{
        width:90,
        height:30,
        backgroundColor:'#ddd',
        alignItems:'center',
        alignSelf:'center',
        marginVertical:15,
        justifyContent:'center'
    },
    TxtVM:{
        fontWeight:'bold',
    },
})
export default styles;