import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    header:{
        flexDirection:'row',
        justifyContent:'flex-start',
        height:50,
        alignItems:'center',
        borderBottomColor:'silver',
        borderBottomWidth:0.5,
        backgroundColor:'#fff'
    },
    Title:{
        fontSize:18,
        fontWeight:'bold',
        marginLeft:10
    },
    numb:{
        flexDirection:'row',
        justifyContent:'center',
        height:50,
        alignItems:'center',
        borderBottomColor:'silver',
        borderBottomWidth:0.5,
        backgroundColor:'#ddd'
    },
    numberT:{
        fontSize:18,
        fontWeight:'bold',
        color:'grey'
    },
    img:{
        width:120,
        height:180,
        marginLeft:10
    },
    fList:{
        backgroundColor:'white',
        height:'auto'
    },
    comp:{
        width:'65%',
        height:'90%',
    },
    ren:{
        flexDirection:'row',
        width:'100%',
        height:200,
        alignItems:'center',
        justifyContent:'space-between'
    },
    top:{
        flexDirection:'row',
        justifyContent:'space-between'
    },
    body:{
        
    },
    size:{
        marginTop:'45%'
    },
})
export default styles